name: build perl on windows

on: [push]

jobs:
  windows:
    runs-on: windows-2019
    strategy:
      matrix:
        perl:
        - "5.30.0"
        - "5.28.2"
        - "5.28.1"
        - "5.28.0"
        - "5.26.3"
        - "5.26.2"
        - "5.26.1"
        - "5.26.0"
        - "5.24.4"
        - "5.24.3"
        - "5.24.2"
        - "5.24.1"
        - "5.24.0"
        # builds fail with these versions, I gave up :(
        # - "5.22.4"
        # - "5.22.3"
        # - "5.22.2"
        # - "5.22.1"
        # - "5.22.0"
        # - "5.20.3"
        # - "5.20.2"
        # - "5.20.1"
        # - "5.20.0"
        # - "5.18.4"
        # - "5.18.3"
        # - "5.18.2"
        # - "5.18.1"
        # - "5.18.0"
        # - "5.16.3"
        # - "5.16.2"
        # - "5.16.1"
        # - "5.16.0"
        # - "5.14.4"
        # - "5.14.3"
        # - "5.14.2"
        # - "5.14.1"
        # - "5.14.0"
        # - "5.12.5"
        # - "5.12.4"
        # - "5.12.3"
        # - "5.12.2"
        # - "5.12.1"
        # - "5.12.0"
        # - "5.10.1"
        # - "5.10.1"
        # - "5.10.0"
        # - "5.8.9"
        # - "5.8.8"
        # - "5.8.7"
        # - "5.8.6"
        # - "5.8.5"
    steps:
    - uses: actions/checkout@v1
    - name: build
      shell: pwsh
      run: |
        C:\Strawberry\perl\bin\perl.exe build-perl-win.pl
      env:
        PERL_VERSION: ${{ matrix.perl }}
      continue-on-error: true

    - name: upload
      shell: pwsh
      run: |
        Set-Location ${env:RUNNER_TEMP}
        Invoke-WebRequest -Uri https://github.com/shogo82148/s3cli-mini/releases/download/v0.0.2/s3cli-mini_windows_amd64.zip -OutFile s3cli-mini.zip
        7z x s3cli-mini.zip
        $pkg = Get-Content "${env:GITHUB_WORKSPACE}/package.json" -Encoding UTF8 -Raw | ConvertFrom-Json
        $version = $pkg.version
        s3cli-mini_windows_amd64/s3cli-mini --region us-east-1 cp --acl public-read perl.zip "s3://shogo82148-actions-setup-perl/v$version/perl-${env:PERL_VERSION}-win32-x64.tar.gz"
      env:
        PERL_VERSION: ${{ matrix.perl }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      continue-on-error: true
